name: miel_work_request_square_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  page_transition: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  alert_banner: ^1.0.1
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  file_picker: ^8.0.5
  file_selector: ^1.0.3
  universal_html: ^2.2.4
  common_utils: ^2.1.0
  board_datetime_picker: ^1.6.8
  calendar_date_picker2: ^1.1.5
  month_picker_dialog: ^4.0.0

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf